/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>

//#include "hal_i2c_driver.h"
//#include "hal_gpio_driver.h"
//#include "i2c_main.h"
//#include "led.h"

/* Uncomment to build as I2C master */
//#define I2C_MASTER_MODE_EN

#define SLAVE_OWN_ADDRESS      (uint8_t)0x53
#define SLAVE_ADDRESS_READ     (uint8_t)0xA7
#define SLAVE_ADDRESS_WRITE    (uint8_t)0xA6

#define GENERAL_CALL_ADDRESS   (uint8_t)0x00

#define MASTER_WRITE_CMD       0xC1
#define MASTER_READ_CMD        0xC2

#define READ_LEN    5
#define WRITE_LEN   5

uint8_t master_tx_buffer[WRITE_LEN] = {0xa5, 0x55, 0xa5, 0x55, 0xb0};
uint8_t master_rx_buffer[READ_LEN];
uint8_t slave_tx_buffer[WRITE_LEN]  = {0xa5, 0x55, 0xa5, 0x55, 0xc0};
uint8_t slave_rx_buffer[READ_LEN];

uint8_t master_write_req;
uint8_t master_read_req;

uint8_t slave_rcv_cmd;


extern void  hal_i2c_enable_peripheral(I2C_TypeDef *i2cx);
extern void  hal_gpio_driver_set_alternate_function(GPIO_TypeDef *GPIOx, uint16_t pin_no, uint16_t alt_fun_value);
extern void  HAL_GPIO_EXTI_IRQHandler(uint16_t GPIO_Pin);
extern void  HAL_NVIC_SetPriority(IRQn_Type IRQn, uint32_t PreemptPriority, uint32_t SubPriority);
extern void  HAL_NVIC_EnableIRQ(IRQn_Type IRQn);



#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif



void delay_gen(void)
{
    uint32_t cnt = 500000;
    while (cnt--);
}

i2c_handle_t i2c_handle;
int TestReady = 0;

void i2c_gpio_init()
{
    gpio_pin_conf_t i2c_scl, i2c_sda;

    _HAL_RCC_GPIOB_CLK_ENABLE();

    i2c_scl.pin = I2C1_SCL_LINE;
    i2c_scl.mode = GPIO_PIN_ALT_FUN_MODE;
    i2c_scl.op_type = GPIO_PIN_OP_TYPE_OPEN_DRAIN;
    i2c_scl.pull = GPIO_PIN_PULL_UP;
    i2c_scl.speed = GPIO_PIN_SPEED_HIGH;

    hal_gpio_set_alt_function(GPIOB, I2C1_SCL_LINE, GPIO_PIN_AF4_I2C123);
    hal_gpio_init(GPIOB, &i2c_scl);

    i2c_sda.pin = I2C1_SDA_LINE;
    i2c_sda.mode = GPIO_PIN_ALT_FUN_MODE;
    i2c_sda.op_type = GPIO_PIN_OP_TYPE_OPEN_DRAIN;
    i2c_sda.pull = GPIO_PIN_PULL_UP;
    i2c_sda.speed = GPIO_PIN_SPEED_HIGH;

    hal_gpio_set_alt_function(GPIOB, I2C1_SDA_LINE, GPIO_PIN_AF4_I2C123);
    hal_gpio_init(GPIOB, &i2c_sda);
}

/**
  * @brief  Compares two buffers.
  * @param  pBuffer1, pBuffer2: buffers to be compared.
  * @param  BufferLength: buffer's length
  * @retval 0  : pBuffer1 identical to pBuffer2
  *         >0 : pBuffer1 differs from pBuffer2
  */
static uint16_t Buffercmp(uint8_t* pBuffer1, uint8_t* pBuffer2, uint16_t BufferLength)
{
  while (BufferLength--)
  {
    if ((*pBuffer1) != *pBuffer2)
    {
      return BufferLength;
    }
    pBuffer1++;
    pBuffer2++;
  }

  return 0;
}

void gpio_btn_interrupt_handler(void)
{
    hal_gpio_clear_interrupt(0);
    TestReady = SET;
}

int main(void)
{
    uint32_t val;
    led_init();

    i2c_gpio_init();

    /* Configure USER Button */
#ifdef I2C_MASTER_MODE_EN
    hal_gpio_configure_interrupt(0, INT_FALLING_EDGE, gpio_btn_interrupt_handler);
#endif

    _HAL_RCC_I2C1_CLK_ENABLE();
        i2c_handle.Instance = I2C_1;
        i2c_handle.Init.ack_enable = I2C_ACK_ENABLE;
        i2c_handle.Init.AddressingMode = I2C_ADDRMODE_7BIT;
        i2c_handle.Init.ClockSpeed = 100000;
        i2c_handle.Init.DutyCycle = I2C_FM_DUTY_2; //care needs to taken
        i2c_handle.Init.GeneralCallMode = 0;
        i2c_handle.Init.NoStretchMode = I2C_ENABLE_CLK_STRETCH;
        i2c_handle.Init.OwnAddress1 = SLAVE_OWN_ADDRESS;

        NVIC_EnableIRQ(I2Cx_ER_IRQn);
        NVIC_EnableIRQ(I2Cx_EV_IRQn);

        hal_i2c_init(&i2c_handle);
        hal_i2c_enable_peripheral(i2c_handle.Instance);

        hal_gpio_enable_interrupt(0);

        i2c_handle.State = HAL_I2C_STATE_READY;

#ifdef I2C_MASTER_MODE_EN
    /* Wait for user Button press before starting the communication. Toggles LED3 until then */
    while (TestReady != SET)
    {
        led_toggle(GPIOD, LED_ORANGE); // LED3 (orange)
        delay_gen();
    }

    /* Loop forever */
	for(;;);
}
